### PUT request to update existing patient
PUT http://localhost:4000/patient-service/api/v1/patients/123e4567-e89b-12d3-a456-426614174003
Content-Type: application/json

{
  "name": "Ishara Deshan",
  "email": "ishara@gmail.com",
  "address": "123 Main St, Colombo",
  "dateOfBirth": "2005-11-06"
}

###
